<a href="https://colab.research.google.com/github/Kishan1082/Deep-Learning/blob/main/CSE_360_Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ANN Model

Employee Retention dataset

In [ ]:
#import the libraries

import numpy as np
import pandas as pd

df = pd.read_csv("/content/HR_comma_sep - HR_comma_sep.csv")

In [ ]:
df

       satisfaction_level  last_evaluation  ...    sales  salary
0                    0.38             0.53  ...    sales     low
1                    0.80             0.86  ...    sales  medium
2                    0.11             0.88  ...    sales  medium
3                    0.72             0.87  ...    sales     low
4                    0.37             0.52  ...    sales     low
...                   ...              ...  ...      ...     ...
14994                0.40             0.57  ...  support     low
14995                0.37             0.48  ...  support     low
14996                0.37             0.53  ...  support     low
14997                0.11             0.96  ...  support     low
14998                0.37             0.52  ...  support     low

[14999 rows x 10 columns]

In [ ]:
df1 =["sales","salary"]
df_final = pd.get_dummies(df, columns=df1, drop_first=True)

In [ ]:
df_final

       satisfaction_level  last_evaluation  ...  salary_low  salary_medium
0                    0.38             0.53  ...           1              0
1                    0.80             0.86  ...           0              1
2                    0.11             0.88  ...           0              1
3                    0.72             0.87  ...           1              0
4                    0.37             0.52  ...           1              0
...                   ...              ...  ...         ...            ...
14994                0.40             0.57  ...           1              0
14995                0.37             0.48  ...           1              0
14996                0.37             0.53  ...           1              0
14997                0.11             0.96  ...           1              0
14998                0.37             0.52  ...           1              0

[14999 rows x 19 columns]

In [ ]:
#spliting x and y variable

X = df_final.drop(['left'], axis =1).values
y = df_final['left'].values

In [ ]:
X

array([[0.38, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.8 , 0.86, 5.  , ..., 0.  , 0.  , 1.  ],
       [0.11, 0.88, 7.  , ..., 0.  , 0.  , 1.  ],
       ...,
       [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
       [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]])

In [ ]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(9, kernel_initializer="uniform", activation = 'relu', input_dim = 18))
model.add(Dense(5, kernel_initializer="uniform", activation ='relu'))
model.add(Dense(1, kernel_initializer= "uniform", activation ="sigmoid"))
model.compile(optimizer='adam', loss="binary_crossentropy", metrics =["accuracy"])

In [ ]:
model.fit(X_train, y_train, epochs=150)

Epoch 1/150
329/329 [==============================] - 3s 4ms/step - loss: 0.5384 - accuracy: 0.7616
Epoch 2/150
329/329 [==============================] - 1s 4ms/step - loss: 0.3753 - accuracy: 0.7631
Epoch 3/150
329/329 [==============================] - 1s 4ms/step - loss: 0.3330 - accuracy: 0.8140
Epoch 4/150
329/329 [==============================] - 1s 4ms/step - loss: 0.3053 - accuracy: 0.8834
Epoch 5/150
329/329 [==============================] - 1s 3ms/step - loss: 0.2845 - accuracy: 0.9094
Epoch 6/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2696 - accuracy: 0.9156
Epoch 7/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2578 - accuracy: 0.9215
Epoch 8/150
329/329 [==============================] - 2s 5ms/step - loss: 0.2476 - accuracy: 0.9253
Epoch 9/150
329/329 [==============================] - 2s 5ms/step - loss: 0.2384 - accuracy: 0.9303
Epoch 10/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2306 - accuracy: 0.9322
Epoch 11/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2240 - accuracy: 0.9344
Epoch 12/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2184 - accuracy: 0.9376
Epoch 13/150
329/329 [==============================] - 2s 5ms/step - loss: 0.2139 - accuracy: 0.9379
Epoch 14/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2095 - accuracy: 0.9393
Epoch 15/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2060 - accuracy: 0.9407
Epoch 16/150
329/329 [==============================] - 2s 5ms/step - loss: 0.2034 - accuracy: 0.9429
Epoch 17/150
329/329 [==============================] - 2s 5ms/step - loss: 0.2014 - accuracy: 0.9427
Epoch 18/150
329/329 [==============================] - 1s 4ms/step - loss: 0.1998 - accuracy: 0.9441
Epoch 19/150
329/329 [==============================] - 1s 3ms/step - loss: 0.1985 - accuracy: 0.9438
Epoch 20/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1972 - accuracy: 0.9451
Epoch 21/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1961 - accuracy: 0.9448
Epoch 22/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1954 - accuracy: 0.9449
Epoch 23/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1949 - accuracy: 0.9437
Epoch 24/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1945 - accuracy: 0.9429
Epoch 25/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1936 - accuracy: 0.9439
Epoch 26/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1934 - accuracy: 0.9434
Epoch 27/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1932 - accuracy: 0.9448
Epoch 28/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1928 - accuracy: 0.9436
Epoch 29/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1924 - accuracy: 0.9439
Epoch 30/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1927 - accuracy: 0.9430
Epoch 31/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1922 - accuracy: 0.9428
Epoch 32/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1916 - accuracy: 0.9444
Epoch 33/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1911 - accuracy: 0.9443
Epoch 34/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1910 - accuracy: 0.9433
Epoch 35/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1896 - accuracy: 0.9443
Epoch 36/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1893 - accuracy: 0.9449
Epoch 37/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1885 - accuracy: 0.9440
Epoch 38/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1873 - accuracy: 0.9455
Epoch 39/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1865 - accuracy: 0.9448
Epoch 40/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1857 - accuracy: 0.9459
Epoch 41/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1848 - accuracy: 0.9449
Epoch 42/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1836 - accuracy: 0.9465
Epoch 43/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1828 - accuracy: 0.9459
Epoch 44/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1818 - accuracy: 0.9469
Epoch 45/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1809 - accuracy: 0.9459
Epoch 46/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1798 - accuracy: 0.9473
Epoch 47/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1784 - accuracy: 0.9478
Epoch 48/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1777 - accuracy: 0.9484
Epoch 49/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1767 - accuracy: 0.9475
Epoch 50/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1758 - accuracy: 0.9470
Epoch 51/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1751 - accuracy: 0.9473
Epoch 52/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1737 - accuracy: 0.9477
Epoch 53/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1726 - accuracy: 0.9482
Epoch 54/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1721 - accuracy: 0.9478
Epoch 55/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1707 - accuracy: 0.9492
Epoch 56/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1699 - accuracy: 0.9489
Epoch 57/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1689 - accuracy: 0.9487
Epoch 58/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1684 - accuracy: 0.9496
Epoch 59/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1675 - accuracy: 0.9495
Epoch 60/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1663 - accuracy: 0.9495
Epoch 61/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1656 - accuracy: 0.9501
Epoch 62/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1650 - accuracy: 0.9499
Epoch 63/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1645 - accuracy: 0.9502
Epoch 64/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1637 - accuracy: 0.9510
Epoch 65/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1631 - accuracy: 0.9496
Epoch 66/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1628 - accuracy: 0.9497
Epoch 67/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1619 - accuracy: 0.9504
Epoch 68/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1616 - accuracy: 0.9512
Epoch 69/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1603 - accuracy: 0.9511
Epoch 70/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1601 - accuracy: 0.9509
Epoch 71/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1594 - accuracy: 0.9509
Epoch 72/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1592 - accuracy: 0.9513
Epoch 73/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1587 - accuracy: 0.9515
Epoch 74/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1585 - accuracy: 0.9512
Epoch 75/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1577 - accuracy: 0.9519
Epoch 76/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1577 - accuracy: 0.9513
Epoch 77/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1570 - accuracy: 0.9514
Epoch 78/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1567 - accuracy: 0.9510
Epoch 79/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1562 - accuracy: 0.9523
Epoch 80/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1561 - accuracy: 0.9514
Epoch 81/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1554 - accuracy: 0.9525
Epoch 82/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1559 - accuracy: 0.9516
Epoch 83/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1552 - accuracy: 0.9517
Epoch 84/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1548 - accuracy: 0.9509
Epoch 85/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1543 - accuracy: 0.9527
Epoch 86/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1545 - accuracy: 0.9514
Epoch 87/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1537 - accuracy: 0.9521
Epoch 88/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1533 - accuracy: 0.9529
Epoch 89/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1535 - accuracy: 0.9517
Epoch 90/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1531 - accuracy: 0.9526
Epoch 91/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1526 - accuracy: 0.9533
Epoch 92/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1529 - accuracy: 0.9524
Epoch 93/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1524 - accuracy: 0.9528
Epoch 94/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1521 - accuracy: 0.9525
Epoch 95/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1520 - accuracy: 0.9530
Epoch 96/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1515 - accuracy: 0.9527
Epoch 97/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1515 - accuracy: 0.9530
Epoch 98/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1515 - accuracy: 0.9536
Epoch 99/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1513 - accuracy: 0.9526
Epoch 100/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1510 - accuracy: 0.9532
Epoch 101/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1506 - accuracy: 0.9529
Epoch 102/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1507 - accuracy: 0.9518
Epoch 103/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1502 - accuracy: 0.9534
Epoch 104/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1500 - accuracy: 0.9530
Epoch 105/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1502 - accuracy: 0.9530
Epoch 106/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1505 - accuracy: 0.9530
Epoch 107/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1496 - accuracy: 0.9538
Epoch 108/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1498 - accuracy: 0.9533
Epoch 109/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1492 - accuracy: 0.9535
Epoch 110/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1493 - accuracy: 0.9525
Epoch 111/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1493 - accuracy: 0.9534
Epoch 112/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1490 - accuracy: 0.9531
Epoch 113/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1490 - accuracy: 0.9534
Epoch 114/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1492 - accuracy: 0.9529
Epoch 115/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1486 - accuracy: 0.9527
Epoch 116/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1486 - accuracy: 0.9523
Epoch 117/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1487 - accuracy: 0.9524
Epoch 118/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1483 - accuracy: 0.9532
Epoch 119/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1483 - accuracy: 0.9529
Epoch 120/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1479 - accuracy: 0.9537
Epoch 121/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1484 - accuracy: 0.9529
Epoch 122/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1479 - accuracy: 0.9532
Epoch 123/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1480 - accuracy: 0.9519
Epoch 124/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1484 - accuracy: 0.9525
Epoch 125/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1478 - accuracy: 0.9523
Epoch 126/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1483 - accuracy: 0.9532
Epoch 127/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1473 - accuracy: 0.9526
Epoch 128/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1471 - accuracy: 0.9537
Epoch 129/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1476 - accuracy: 0.9529
Epoch 130/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1477 - accuracy: 0.9527
Epoch 131/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1478 - accuracy: 0.9529
Epoch 132/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1469 - accuracy: 0.9529
Epoch 133/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1471 - accuracy: 0.9538
Epoch 134/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1473 - accuracy: 0.9528
Epoch 135/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1470 - accuracy: 0.9526
Epoch 136/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1471 - accuracy: 0.9519
Epoch 137/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1470 - accuracy: 0.9522
Epoch 138/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1469 - accuracy: 0.9520
Epoch 139/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1469 - accuracy: 0.9529
Epoch 140/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1466 - accuracy: 0.9521
Epoch 141/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1467 - accuracy: 0.9522
Epoch 142/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1466 - accuracy: 0.9522
Epoch 143/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1464 - accuracy: 0.9536
Epoch 144/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1465 - accuracy: 0.9520
Epoch 145/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1465 - accuracy: 0.9532
Epoch 146/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1464 - accuracy: 0.9533
Epoch 147/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1462 - accuracy: 0.9523
Epoch 148/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1465 - accuracy: 0.9526
Epoch 149/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1461 - accuracy: 0.9526
Epoch 150/150
329/329 [==============================] - 1s 2ms/step - loss: 0.1461 - accuracy: 0.9532

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([[3.4000903e-05],
       [4.2078376e-02],
       [9.4962120e-03],
       ...,
       [3.4567714e-03],
       [1.2172222e-02],
       [8.1912905e-01]], dtype=float32)

In [ ]:
y_pred = y_pred.round()
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]], dtype=float32)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.9508888888888889

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3312,  104],
       [ 117,  967]])

Churn Model dataset

In [ ]:
df = pd.read_csv("/content/Churn_Modelling.csv")
df

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [ ]:
df_drop =df.iloc[:, 0:3]

In [ ]:
df_final=df.drop(df_drop, axis=1)
df_final

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [ ]:
df_final.shape

(10000, 11)

In [ ]:
#One hot encoding of categorical data
df1 =['Geography','Gender']
df_final = pd.get_dummies(df_final,columns=df1,drop_first=True)
df_final.head()

   CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...                  0                0            0
1          608   41       1  ...                  0                1            0
2          502   42       8  ...                  0                0            0
3          699   39       1  ...                  0                0            0
4          850   43       2  ...                  0                1            0

[5 rows x 12 columns]

In [ ]:
# Split the independent and dependent variables
X = df_final.drop(['Exited'],axis=1)
y = df_final['Exited']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [ ]:
# Standardising the data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = Sequential()

# Input Layer
ann.add(Dense(12, input_dim=11,kernel_initializer='uniform',activation='relu'))

# Hidden layer
ann.add(Dense(8,activation='relu'))

# Output layer
ann.add(Dense(1,activation='sigmoid'))

In [ ]:
# compile the model
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# Fit the model
res = ann.fit(X_train,y_train,batch_size=32,epochs= 200)

Epoch 1/200
219/219 [==============================] - 1s 3ms/step - loss: 0.5585 - accuracy: 0.7780
Epoch 2/200
219/219 [==============================] - 1s 3ms/step - loss: 0.4133 - accuracy: 0.8214
Epoch 3/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3932 - accuracy: 0.8299
Epoch 4/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3833 - accuracy: 0.8314
Epoch 5/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3754 - accuracy: 0.8351
Epoch 6/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3680 - accuracy: 0.8343
Epoch 7/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3606 - accuracy: 0.8400
Epoch 8/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3548 - accuracy: 0.8501
Epoch 9/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3499 - accuracy: 0.8593
Epoch 10/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3452 - accuracy: 0.8579
Epoch 11/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3433 - accuracy: 0.8613
Epoch 12/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3396 - accuracy: 0.8631
Epoch 13/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8640
Epoch 14/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3367 - accuracy: 0.8619
Epoch 15/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3354 - accuracy: 0.8633
Epoch 16/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3344 - accuracy: 0.8616
Epoch 17/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3337 - accuracy: 0.8624
Epoch 18/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8623
Epoch 19/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3311 - accuracy: 0.8634
Epoch 20/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3318 - accuracy: 0.8656
Epoch 21/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3308 - accuracy: 0.8631
Epoch 22/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3298 - accuracy: 0.8630
Epoch 23/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3299 - accuracy: 0.8643
Epoch 24/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3299 - accuracy: 0.8623
Epoch 25/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3287 - accuracy: 0.8634
Epoch 26/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3277 - accuracy: 0.8637
Epoch 27/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3285 - accuracy: 0.8636
Epoch 28/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3281 - accuracy: 0.8651
Epoch 29/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3270 - accuracy: 0.8629
Epoch 30/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3263 - accuracy: 0.8644
Epoch 31/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3266 - accuracy: 0.8637
Epoch 32/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3260 - accuracy: 0.8639
Epoch 33/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3256 - accuracy: 0.8647
Epoch 34/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3253 - accuracy: 0.8651
Epoch 35/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3249 - accuracy: 0.8663
Epoch 36/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3243 - accuracy: 0.8641
Epoch 37/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3242 - accuracy: 0.8670
Epoch 38/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3235 - accuracy: 0.8640
Epoch 39/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3236 - accuracy: 0.8660
Epoch 40/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3229 - accuracy: 0.8646
Epoch 41/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3240 - accuracy: 0.8654
Epoch 42/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3221 - accuracy: 0.8669
Epoch 43/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3220 - accuracy: 0.8681
Epoch 44/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3220 - accuracy: 0.8681
Epoch 45/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3217 - accuracy: 0.8657
Epoch 46/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3216 - accuracy: 0.8659
Epoch 47/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3226 - accuracy: 0.8659
Epoch 48/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3215 - accuracy: 0.8639
Epoch 49/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3210 - accuracy: 0.8659
Epoch 50/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8653
Epoch 51/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3206 - accuracy: 0.8673
Epoch 52/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3200 - accuracy: 0.8653
Epoch 53/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3203 - accuracy: 0.8683
Epoch 54/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3206 - accuracy: 0.8667
Epoch 55/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3192 - accuracy: 0.8670
Epoch 56/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3197 - accuracy: 0.8646
Epoch 57/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8646
Epoch 58/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3192 - accuracy: 0.8677
Epoch 59/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3187 - accuracy: 0.8674
Epoch 60/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3188 - accuracy: 0.8661
Epoch 61/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3185 - accuracy: 0.8653
Epoch 62/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8666
Epoch 63/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3181 - accuracy: 0.8677
Epoch 64/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3179 - accuracy: 0.8649
Epoch 65/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3178 - accuracy: 0.8676
Epoch 66/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3173 - accuracy: 0.8673
Epoch 67/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3182 - accuracy: 0.8677
Epoch 68/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3173 - accuracy: 0.8651
Epoch 69/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3171 - accuracy: 0.8669
Epoch 70/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3169 - accuracy: 0.8671
Epoch 71/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3171 - accuracy: 0.8664
Epoch 72/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3168 - accuracy: 0.8674
Epoch 73/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3174 - accuracy: 0.8651
Epoch 74/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3171 - accuracy: 0.8656
Epoch 75/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3163 - accuracy: 0.8686
Epoch 76/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3171 - accuracy: 0.8649
Epoch 77/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3168 - accuracy: 0.8671
Epoch 78/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3160 - accuracy: 0.8681
Epoch 79/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3163 - accuracy: 0.8664
Epoch 80/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3166 - accuracy: 0.8664
Epoch 81/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3154 - accuracy: 0.8680
Epoch 82/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3156 - accuracy: 0.8677
Epoch 83/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3158 - accuracy: 0.8689
Epoch 84/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3154 - accuracy: 0.8684
Epoch 85/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3159 - accuracy: 0.8689
Epoch 86/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3153 - accuracy: 0.8657
Epoch 87/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3150 - accuracy: 0.8693
Epoch 88/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3149 - accuracy: 0.8673
Epoch 89/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3144 - accuracy: 0.8684
Epoch 90/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3142 - accuracy: 0.8671
Epoch 91/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3145 - accuracy: 0.8689
Epoch 92/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3147 - accuracy: 0.8661
Epoch 93/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3145 - accuracy: 0.8679
Epoch 94/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3144 - accuracy: 0.8686
Epoch 95/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3149 - accuracy: 0.8669
Epoch 96/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3137 - accuracy: 0.8653
Epoch 97/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3135 - accuracy: 0.8681
Epoch 98/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3139 - accuracy: 0.8691
Epoch 99/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3139 - accuracy: 0.8683
Epoch 100/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3138 - accuracy: 0.8676
Epoch 101/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3135 - accuracy: 0.8684
Epoch 102/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3136 - accuracy: 0.8676
Epoch 103/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3136 - accuracy: 0.8653
Epoch 104/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3136 - accuracy: 0.8679
Epoch 105/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3132 - accuracy: 0.8681
Epoch 106/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3134 - accuracy: 0.8694
Epoch 107/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3128 - accuracy: 0.8680
Epoch 108/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3134 - accuracy: 0.8674
Epoch 109/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3129 - accuracy: 0.8674
Epoch 110/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3139 - accuracy: 0.8691
Epoch 111/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3130 - accuracy: 0.8683
Epoch 112/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3128 - accuracy: 0.8683
Epoch 113/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3125 - accuracy: 0.8687
Epoch 114/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3125 - accuracy: 0.8704
Epoch 115/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3122 - accuracy: 0.8686
Epoch 116/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3127 - accuracy: 0.8691
Epoch 117/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3126 - accuracy: 0.8680
Epoch 118/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3118 - accuracy: 0.8689
Epoch 119/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3123 - accuracy: 0.8696
Epoch 120/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3120 - accuracy: 0.8700
Epoch 121/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3125 - accuracy: 0.8686
Epoch 122/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3129 - accuracy: 0.8673
Epoch 123/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3119 - accuracy: 0.8673
Epoch 124/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3113 - accuracy: 0.8707
Epoch 125/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3118 - accuracy: 0.8684
Epoch 126/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3110 - accuracy: 0.8680
Epoch 127/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3112 - accuracy: 0.8711
Epoch 128/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8694
Epoch 129/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3114 - accuracy: 0.8669
Epoch 130/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3117 - accuracy: 0.8680
Epoch 131/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8694
Epoch 132/200
219/219 [==============================] - 1s 4ms/step - loss: 0.3126 - accuracy: 0.8686
Epoch 133/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3112 - accuracy: 0.8696
Epoch 134/200
219/219 [==============================] - 1s 4ms/step - loss: 0.3109 - accuracy: 0.8677
Epoch 135/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3111 - accuracy: 0.8687
Epoch 136/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3107 - accuracy: 0.8697
Epoch 137/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3116 - accuracy: 0.8703
Epoch 138/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3113 - accuracy: 0.8693
Epoch 139/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3108 - accuracy: 0.8690
Epoch 140/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3110 - accuracy: 0.8681
Epoch 141/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3112 - accuracy: 0.8691
Epoch 142/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3114 - accuracy: 0.8683
Epoch 143/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3104 - accuracy: 0.8696
Epoch 144/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3108 - accuracy: 0.8690
Epoch 145/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3107 - accuracy: 0.8684
Epoch 146/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3104 - accuracy: 0.8673
Epoch 147/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3114 - accuracy: 0.8694
Epoch 148/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3102 - accuracy: 0.8707
Epoch 149/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3106 - accuracy: 0.8694
Epoch 150/200
219/219 [==============================] - 1s 5ms/step - loss: 0.3107 - accuracy: 0.8683
Epoch 151/200
219/219 [==============================] - 1s 6ms/step - loss: 0.3105 - accuracy: 0.8693
Epoch 152/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3107 - accuracy: 0.8689
Epoch 153/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3099 - accuracy: 0.8697
Epoch 154/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3103 - accuracy: 0.8690
Epoch 155/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3105 - accuracy: 0.8681
Epoch 156/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3103 - accuracy: 0.8684
Epoch 157/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3100 - accuracy: 0.8700
Epoch 158/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3098 - accuracy: 0.8701
Epoch 159/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3095 - accuracy: 0.8693
Epoch 160/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3107 - accuracy: 0.8697
Epoch 161/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3102 - accuracy: 0.8699
Epoch 162/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3100 - accuracy: 0.8694
Epoch 163/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3097 - accuracy: 0.8694
Epoch 164/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3103 - accuracy: 0.8691
Epoch 165/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3097 - accuracy: 0.8693
Epoch 166/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3098 - accuracy: 0.8674
Epoch 167/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3097 - accuracy: 0.8694
Epoch 168/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3103 - accuracy: 0.8687
Epoch 169/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3103 - accuracy: 0.8684
Epoch 170/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3097 - accuracy: 0.8694
Epoch 171/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3095 - accuracy: 0.8710
Epoch 172/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3108 - accuracy: 0.8693
Epoch 173/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3094 - accuracy: 0.8690
Epoch 174/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3105 - accuracy: 0.8704
Epoch 175/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3095 - accuracy: 0.8700
Epoch 176/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3094 - accuracy: 0.8701
Epoch 177/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3097 - accuracy: 0.8681
Epoch 178/200
219/219 [==============================] - 1s 5ms/step - loss: 0.3099 - accuracy: 0.8690
Epoch 179/200
219/219 [==============================] - 1s 5ms/step - loss: 0.3096 - accuracy: 0.8666
Epoch 180/200
219/219 [==============================] - 1s 4ms/step - loss: 0.3097 - accuracy: 0.8697
Epoch 181/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3092 - accuracy: 0.8689
Epoch 182/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3095 - accuracy: 0.8691
Epoch 183/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3092 - accuracy: 0.8687
Epoch 184/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3091 - accuracy: 0.8703
Epoch 185/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3095 - accuracy: 0.8684
Epoch 186/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3096 - accuracy: 0.8689
Epoch 187/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3094 - accuracy: 0.8697
Epoch 188/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3094 - accuracy: 0.8694
Epoch 189/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3091 - accuracy: 0.8707
Epoch 190/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3091 - accuracy: 0.8700
Epoch 191/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3089 - accuracy: 0.8687
Epoch 192/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3080 - accuracy: 0.8697
Epoch 193/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3089 - accuracy: 0.8696
Epoch 194/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3093 - accuracy: 0.8707
Epoch 195/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3087 - accuracy: 0.8680
Epoch 196/200

In [ ]:
y_pred = np.round(ann.predict(X_test)).astype(int)

In [ ]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[2290,   88],
       [ 343,  279]])

In [ ]:
round(accuracy_score(y_test,y_pred),4)*100

85.63

# CNN model

In [ ]:
from keras.datasets import mnist
from keras.layers import Dropout, Conv2D, MaxPool2D, Flatten
from keras.utils import np_utils

In [ ]:
#to calculate accuracy
from sklearn.metrics import accuracy_score

# loading the dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 0s 0us/step
11501568/11490434 [==============================] - 0s 0us/step

In [ ]:
# building the input vector from the 28x28 pixels
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28,1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [ ]:
#normalizing the data to help with the training
X_train /= 255
X_test /= 255

In [ ]:
# One hot encoding using keras numpy related utilities
n_classes = 10
print("before encoding:",y_train.shape)
y_train = np_utils.to_categorical(y_train,n_classes)
y_test = np_utils.to_categorical(y_test,n_classes)
print("After encoding:",y_train.shape)

before encoding: (60000,)
After encoding: (60000, 10)

In [ ]:
# building a linear stack of layers with the sequential model
model = Sequential()
#convultional layer
model.add(Conv2D(32, kernel_size=(3,3), strides=(1,1), padding='valid', activation='relu', input_shape =(28, 28, 1)))
model.add(MaxPool2D(pool_size=(1,1)))
#flatten output of conv
model.add(Flatten())
#hidden layer
model.add(Dense(100, activation='relu'))
#output layer
model.add(Dense(10, activation ='softmax'))

#compiling the sequential model
model.compile(loss = 'categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [ ]:
#training the model for 10 epochs
model.fit(X_train, y_train, batch_size=120, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
500/500 [==============================] - 72s 143ms/step - loss: 0.1762 - accuracy: 0.9493 - val_loss: 0.0728 - val_accuracy: 0.9774
Epoch 2/10
500/500 [==============================] - 62s 125ms/step - loss: 0.0551 - accuracy: 0.9836 - val_loss: 0.0563 - val_accuracy: 0.9817
Epoch 3/10
500/500 [==============================] - 46s 93ms/step - loss: 0.0330 - accuracy: 0.9901 - val_loss: 0.0556 - val_accuracy: 0.9820
Epoch 4/10
500/500 [==============================] - 47s 94ms/step - loss: 0.0201 - accuracy: 0.9941 - val_loss: 0.0524 - val_accuracy: 0.9833
Epoch 5/10
500/500 [==============================] - 46s 93ms/step - loss: 0.0129 - accuracy: 0.9961 - val_loss: 0.0534 - val_accuracy: 0.9830
Epoch 6/10
500/500 [==============================] - 47s 93ms/step - loss: 0.0086 - accuracy: 0.9975 - val_loss: 0.0554 - val_accuracy: 0.9826
Epoch 7/10
500/500 [==============================] - 47s 94ms/step - loss: 0.0069 - accuracy: 0.9981 - val_loss: 0.0570 - val_accuracy: 0.9840
Epoch 8/10
500/500 [==============================] - 47s 93ms/step - loss: 0.0057 - accuracy: 0.9984 - val_loss: 0.0551 - val_accuracy: 0.9852
Epoch 9/10
500/500 [==============================] - 46s 93ms/step - loss: 0.0044 - accuracy: 0.9987 - val_loss: 0.0622 - val_accuracy: 0.9828
Epoch 10/10
500/500 [==============================] - 47s 95ms/step - loss: 0.0049 - accuracy: 0.9983 - val_loss: 0.0622 - val_accuracy: 0.9856

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 26, 26, 32)        320

 max_pooling2d (MaxPooling2D  (None, 26, 26, 32)       0
 )

 flatten (Flatten)           (None, 21632)             0

 dense_6 (Dense)             (None, 100)               2163300

 dense_7 (Dense)             (None, 10)                1010

=================================================================
Total params: 2,164,630
Trainable params: 2,164,630
Non-trainable params: 0
_________________________________________________________________